name: yt_cors_proxy
description: A YouTube CORS Proxy Server.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.1.2
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^3.0.0
